baseURL = "https://ubuntuswik.github.io/link-slate/"
languageCode = "en-us"
title = "linkslate"
theme = "slate"

publishDir = "docs"

[ params ]
Favicon = "favicon.ico"
OpenLinksInNewWindow = true

[[ params.nav ]]
name = "Git"
tag = "git"
icon = "git"

[[ params.nav ]]
name = "Qiita"
tag = "qiita"
icon = "quora"

[[ params.nav ]]
name = "Laravel"
tag = "laravel"
icon = "lastfm"

[[ params.nav ]]
name = "Javascript"
tag = "javascript"
icon = "eject"

[[ params.nav ]]
name = "Python"
tag = "python"
icon = "cubes"

[[ params.nav ]]
name = "Vue.js"
tag = "vue"
icon = "vimeo-square"