baseURL = "https://nob-swik.github.io/link-slate/"
languageCode = "en-us"
title = "linkslate"
theme = "slate"

publishDir = "docs"

[ params ]
Favicon = "favicon.ico"
OpenLinksInNewWindow = true

[[ params.nav ]]
name = "Qiita"
tag = "qiita"
icon = "quora"

[[ params.nav ]]
name = "PHP"
tag = "PHP"
icon = "p"

[[ params.nav ]]
name = "Javascript"
tag = "javascript"
icon = "js"

[[ params.nav ]]
name = "SQL"
tag = "SQL"
icon = "database"

[[ params.nav ]]
name = "React"
tag = "react"
icon = "react"

[[ params.nav ]]
name = "OTHERS"
tag = "others"
icon = "asterisk"