baseURL = "https://ubuntuswik.github.io/link-slate/"
languageCode = "en-us"
title = "linkslate"
theme = "slate"

publishDir = "docs"

[ params ]
Favicon = "favicon.ico"
OpenLinksInNewWindow = true

[[ params.nav ]]
name = "Git"
tag = "git"
icon = "git"

[[ params.nav ]]
name = "Qiita"
tag = "qiita"
icon = "quora"

[[ params.nav ]]
name = "Laravel"
tag = "laravel"
icon = "laravel"

[[ params.nav ]]
name = "Javascript"
tag = "javascript"
icon = "js"

[[ params.nav ]]
name = "Python"
tag = "python"
icon = "python"